site_name: AI Verify Developer Documentation
site_url: http://127.0.0.1/

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2023 AI Verify</a>

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_if_no_docstring: true
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: true
            show_object_full_path: true
            show_root_members_full_path: true
            show_category_heading: true
            show_signature_annotations: false
            group_by_category: true
            heading_level: 2

nav:
  - Home: index.md
  - Getting Started: 
    - Start Here: getting_started/start_here.md
    - Installing AI Verify Developer Tools: getting_started/install_aiverify_dev_tools.md
    - Guided Example:
      - Introduction to Plugins: guided_example/introduction_to_plugins.md
      - Create Your First Algorithm: guided_example/your_first_algorithm.md
      - Create Your First Widget: guided_example/your_first_widget.md
      - Deploy Your Plugin: guided_example/deploy_your_plugin.md
  - Plugin System: 
    - Plugin System: plugins/index.md
    - Algorithm: 
      - Project Structure: plugins/algorithm/file_structure.md
      - Core Modules: plugins/algorithm/core_modules.md
      - Testing: plugins/algorithm/testing_algorithm.md
      - Deploying: plugins/algorithm/deploying_algorithm.md
    - Widget & Input Block:
      - Input Block: plugins/widget/InputBlock.md
      - Widget: plugins/widget/Widget.md
      - AI Verify Frontend Shared Library: plugins/widget/Shared_Library.md
      - AI Verify Frontend Plugin Tool: plugins/widget/Plugin_Tool.md
      - MDX Guide: plugins/widget/MDX_Guide.md
    - Report Template:
      - Template: plugins/widget/Template.md
  - AI Verify Stock Plugins:
    - AI Verify Stock Plugins: stock_plugins/index.md
    - Fairness for Classification: stock_plugins/fmtc.md
    - Fairness for Regression: stock_plugins/fmtr.md
    - Robustness Toolbox: stock_plugins/robustness_toolbox.md
    - SHAP: stock_plugins/shap.md
    - Partial Dependence Plot: stock_plugins/pdp.md
    - Accumulated Local Effect: stock_plugins/ale.md
    - Image Corruption Toolbox: stock_plugins/image_corruption.md
    - Stock Reports: stock_plugins/report.md
    - Process Checklist: stock_plugins/process_checklist.md
    - Decorators: stock_plugins/decorators.md
